### ISSUE TITLE
APC Diagnostic Test Status Missing, Breaking Alert Templates

### ISSUE THREAD

**Issue by sjtarik** [librenms/librenms#13494]
### The problem

After discovery moved to yaml based method, I guess a few OIDs not included for UPS devices. But there are template alerts for APC and generic UPS alerts like "UPS Switched to Battery Power" that depends on these fields. upsAdvTestDiagnosticsResults is one of them. 

Adding following snippet to includes/definitions/discovery/apc.yaml file and rediscovering the device fixed the issue for APC UPS'es. 

```
                    oid: upsAdvTestDiagnosticsResults
                    num_oid: '.1.3.6.1.4.1.318.1.1.1.7.2.3.0'
                    descr: UPS diagnostics status
                    states:
                        - { descr: ok, graph: 0, value: 1, generic: 0 }
                        - { descr: failed, graph: 0, value: 2, generic: 3 }
                        - { descr: invalidTest, graph: 0, value: 3, generic: 1 }
                        - { descr: testInProgress, graph: 0, value: 4, generic: 1 }
```

### Output of ./validate.php

```txt
n/a
```
